import { createHash } from "node:crypto";
import { join } from "node:path";

export const SERVICE_LABEL = "dev.herdr.herdr-gui";
export const GENERATED_MARKER = "Generated by herdr-gui service install.";

export type ServicePlatform = "systemd" | "launchd" | "windows-task";

export interface ServicePaths {
  config: string;
  definition: string;
  taskName?: string;
  stdoutLog?: string;
  stderrLog?: string;
}

export const DEFAULT_SERVICE_ENV_FILE = `# herdr-gui service environment
# This file is preserved by \`herdr-gui service install\`.
HOST=0.0.0.0
PORT=8787

# Optional fixed password. By default, service install creates a generated token.
# HERDR_GUI_PASSWORD=replace-with-a-strong-password

# Operational logs default to info. Use debug only while diagnosing an issue.
# HERDR_GUI_LOG_LEVEL=info

# Optional Herdr connection settings.
# HERDR_SOCKET_PATH=/path/to/herdr.sock
# HERDR_CLIENT_SOCKET_PATH=/path/to/herdr-client.sock
# HERDR_SSH_HOST=user@example.com
`;

export function resolveServicePlatform(platform: string): ServicePlatform {
  if (platform === "linux") return "systemd";
  if (platform === "darwin") return "launchd";
  if (platform === "win32") return "windows-task";
  throw new Error(`service management is not supported on ${platform}`);
}

export function resolveServicePaths(
  platform: ServicePlatform,
  homeDir: string,
  appDataDir?: string,
): ServicePaths {
  if (platform === "windows-task") {
    const base = join(
      appDataDir ?? join(homeDir, "AppData", "Roaming"),
      "herdr-gui",
    );
    const config = join(base, "herdr-gui.env");
    const userKey = createHash("sha256")
      .update(base.toLowerCase())
      .digest("hex")
      .slice(0, 16);
    return {
      config,
      definition: join(base, "herdr-gui-task.ps1"),
      taskName: `${SERVICE_LABEL}-${userKey}`,
      stdoutLog: join(base, "herdr-gui.stdout.log"),
      stderrLog: join(base, "herdr-gui.stderr.log"),
    };
  }

  const config = join(homeDir, ".config", "herdr-gui", "herdr-gui.env");
  if (platform === "systemd") {
    return {
      config,
      definition: join(
        homeDir,
        ".config",
        "systemd",
        "user",
        "herdr-gui.service",
      ),
    };
  }
  return {
    config,
    definition: join(
      homeDir,
      "Library",
      "LaunchAgents",
      `${SERVICE_LABEL}.plist`,
    ),
    stdoutLog: join(homeDir, "Library", "Logs", "herdr-gui.stdout.log"),
    stderrLog: join(homeDir, "Library", "Logs", "herdr-gui.stderr.log"),
  };
}

export function escapeSystemdExecPath(value: string): string {
  let escaped = "";
  for (const character of value) {
    if (/^[A-Za-z0-9/_.:@+-]$/.test(character)) {
      escaped += character;
      continue;
    }
    if (character === "%") {
      escaped += "%%";
      continue;
    }
    for (const byte of Buffer.from(character, "utf8")) {
      escaped += `\\x${byte.toString(16).padStart(2, "0")}`;
    }
  }
  return escaped;
}

function xmlEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

export function renderSystemdService(
  binaryPath: string,
  configPath: string,
  preservedExecStart?: string,
): string {
  return `# ${GENERATED_MARKER}
[Unit]
Description=Roamgate
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
EnvironmentFile=-${escapeSystemdExecPath(configPath)}
ExecStart=${preservedExecStart ?? escapeSystemdExecPath(binaryPath)}
Restart=always
RestartSec=2
TimeoutStopSec=15

[Install]
WantedBy=default.target
`;
}

function powershellSingleQuotedString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function renderWindowsTaskDefinition(
  binaryPath: string,
  paths: ServicePaths,
): string {
  if (!paths.taskName) throw new Error("Windows service task name is missing");
  const taskName = powershellSingleQuotedString(paths.taskName);
  const executable = powershellSingleQuotedString(binaryPath);
  const argumentsValue = powershellSingleQuotedString(
    `service run "${paths.config}"`,
  );

  return `\uFEFF# ${GENERATED_MARKER}
$ErrorActionPreference = "Stop"
$taskName = ${taskName}
$user = [Security.Principal.WindowsIdentity]::GetCurrent().Name
$action = New-ScheduledTaskAction -Execute ${executable} -Argument ${argumentsValue}
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $user
$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
`;
}

export function renderLaunchdService(
  binaryPath: string,
  paths: ServicePaths,
): string {
  const programArguments = [
    "/bin/sh",
    "-c",
    'set -a; if [ -f "$1" ]; then . "$1"; fi; set +a; exec "$2"',
    "herdr-gui-service",
    paths.config,
    binaryPath,
  ]
    .map((argument) => `    <string>${xmlEscape(argument)}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${GENERATED_MARKER} -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${SERVICE_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
${programArguments}
  </array>

  <key>EnvironmentVariables</key>
  <dict>
    <key>HERDR_GUI_RESTART_SUPERVISOR</key>
    <string>1</string>
  </dict>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>2</integer>
  <key>ProcessType</key>
  <string>Background</string>

  <key>StandardOutPath</key>
  <string>${xmlEscape(paths.stdoutLog ?? "")}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(paths.stderrLog ?? "")}</string>
</dict>
</plist>
`;
}
